version: '3.5'

networks:
  webnet:
    driver: overlay
    attachable: true

services:
  web:
    image: "astorre/griffin_bot:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - config/docker.env
    networks:
      - webnet
